export CC=gcc
export CFLAGS=-std=c99 -g -finline-functions -fno-stack-protector -ffreestanding -m32 -masm=intel -I $(PWD)/include

export LD=ld
export LDFLAGS=-melf_i386 -Tlink.ld

export AS=nasm
export ASFLAGS=-f elf

export WARNING=-Wall -Wextra -Wno-unused-function -Wno-unused-parameter
