#ifndef _VGA_PWN
#define _VGA_PWN

#define VGA_GREY_ON_BLACK (COLOR_LIGHT_GREY | COLOR_BLACK << 4)
#define VGA_RED_ON_BLACK (COLOR_RED | COLOR_BLACK << 4)
#define VGA_WHITE_ON_BLACK (COLOR_WHITE | COLOR_BLACK << 4)
#define VGA_BLACK_ON_WHITE (COLOR_BLACK | COLOR_WHITE << 4)
#define VGA_COLOR(a, b) (a | b << 4)


enum vga_color
{
	COLOR_BLACK = 0,
	COLOR_BLUE = 1,
	COLOR_GREEN = 2,
	COLOR_CYAN = 3,
	COLOR_RED = 4,
	COLOR_MAGENTA = 5,
	COLOR_BROWN = 6,
	COLOR_LIGHT_GREY = 7,
	COLOR_DARK_GREY = 8,
	COLOR_LIGHT_BLUE = 9,
	COLOR_LIGHT_GREEN = 10,
	COLOR_LIGHT_CYAN = 11,
	COLOR_LIGHT_RED = 12,
	COLOR_LIGHT_MAGENTA = 13,
	COLOR_LIGHT_BROWN = 14,
	COLOR_WHITE = 15,
};

#endif
